#+PROPERTY: header-args:R   :cache yes :session readme-r :results value :exports both
#+OPTIONS: toc:nil

* cvar

# from README.md in readxl https://raw.githubusercontent.com/tidyverse/readxl/master/README.md
#
#  build status (travis?)
# [![Travis-CI Build Status](https://travis-ci.org/tidyverse/readxl.svg?branch=master)](https://travis-ci.org/tidyverse/readxl)
#
# build status (appveyor?)
# [![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/tidyverse/readxl?branch=master&svg=true)](https://ci.appveyor.com/project/tidyverse/readxl)
#
# coverage
# [![Coverage Status](https://img.shields.io/codecov/c/github/tidyverse/readxl/master.svg)](https://codecov.io/github/tidyverse/readxl?branch=master)
#
# version
# [![CRAN\_Status\_Badge](https://www.r-pkg.org/badges/version/readxl)](https://cran.r-project.org/package=readxl)
#
# [![lifecycle](https://img.shields.io/badge/lifecycle-stable-brightgreen.svg)](https://www.tidyverse.org/lifecycle/#stable)



[![[https://cran.r-project.org/package=Rdpack][CRAN_Status_Badge]]]


** Overviewmm

Compute expected shortfall (ES) and Value at Risk (VaR) from a
quantile function, distribution function, random number generator or
probability density function.  ES is also known as Conditional Value
at Risk (CVaR). Virtually any continuous distribution can be
specified.  The functions are vectorised over the arguments.
The computations are done directly from the definitions, see e.g. Acerbi
and Tasche (2002).

** Installing cvar

The [[https://cran.r-project.org/package=cvar][latest stable version]] is on CRAN. 
#+BEGIN_EXAMPLE
install_packages("cvar")
#+END_EXAMPLE
The vignette shipping with the package gives illustrative examples.
=vignette("Guide_cvar", package = "cvar")=.
(Due to a mixed-up index entry, it appears to have a puzzling title on the [[https://cran.r-project.org/package=cvar][CRAN cvar page]],
but clicking on it brings up the correct vignette.)


You can install the [[https://github.com/GeoBosh/cvar][development version]] of =cvar= from Github:
#+BEGIN_EXAMPLE
library(devtools)
install_github("GeoBosh/cvar")
#+END_EXAMPLE

** Overview

Package =cvar= is a small =R= package with, essentially two
functions --- =ES= for computing the expected shortfall
and =VaR= for Value at Risk.  The user specifies the
distribution by supplying one of the functions that define a
continuous distribution---currently this can be a quantile
function (qf), cumulative distribution function (cdf) or
probability density function (pdf). Virtually any continuous
distribution can be specified.

The functions are vectorised over the parameters of the
distributions, making bulk computations more convenient, for
example for forecasting or model evaluation.

The name of this package, "cvar", comes from /Conditional Value at
Risk/ (CVaR), which is an alternative term for expected shortfall.

We chose to use the standard names =ES= and =VaR=,
despite the possibility for name clashes with same named
functions in other packages, rather than invent possibly
difficult to remember alternatives. Just call the functions as
=cvar::ES= and =cvar::VaR= if necessary.

Locations-scale transformations can be specified separately
from the other distribution parameters. This is useful when
such parameters are not provided directly by the distribution
at hand. The use of these parameters often leads to more
efficient computations and better numerical accuracy even if
the distribution has its own parameters for this purpose. Some
of the examples for =VaR= and =ES= illustrate this
for the Gaussian distribution.

Since VaR is a quantile, functions computing it for a given
distribution are convenience functions. =VaR= exported by
=cvar= could be attractive in certain workflows because of
its vectorised distribution parameters, the location-scale
transformation and the possibility to compute it from cdf's
when quantile functions are not available.
